name: "rickvandeloo.com"
description: "Homepage of Rick van de Loo"
url: "http://rickvandeloo.com"
paginate: 3
paginate_path: "/page:num/"
markdown: rdiscount
permalink: pretty
highlighter: pygments
exclude: [build.sh, generated]
